"""empty message

Revision ID: 1bbd3d5c9c45
Revises: d24fe233d5f6
Create Date: 2020-09-08 00:08:35.736550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bbd3d5c9c45'
down_revision = 'd24fe233d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ishop_users', sa.Column('user_passwd_hash_real', sa.String(length=128), nullable=False))
    op.drop_column('ishop_users', '_user_passwd_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ishop_users', sa.Column('_user_passwd_hash', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('ishop_users', 'user_passwd_hash_real')
    # ### end Alembic commands ###
