"""empty message

Revision ID: 1ec4b79005fc
Revises: 59424c36834f
Create Date: 2020-09-07 23:59:55.777707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ec4b79005fc'
down_revision = '59424c36834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ishop_users', '_user_passwd_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ishop_users', sa.Column('_user_passwd_hash', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
