"""empty message

Revision ID: 5152dbb6b370
Revises: 7fe3f2aa7e07
Create Date: 2020-09-07 23:46:30.278556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5152dbb6b370'
down_revision = '7fe3f2aa7e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ishop_togethers_ibfk_1', 'ishop_togethers', type_='foreignkey')
    op.create_foreign_key(None, 'ishop_togethers', 'ishop_goods', ['good_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ishop_togethers', type_='foreignkey')
    op.create_foreign_key('ishop_togethers_ibfk_1', 'ishop_togethers', 'ishop_users', ['good_id'], ['id'])
    # ### end Alembic commands ###
