"""empty message

Revision ID: 7fe3f2aa7e07
Revises: 030645f0b0a3
Create Date: 2020-09-07 23:38:03.092298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fe3f2aa7e07'
down_revision = '030645f0b0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ishop_users', 'user_passwd_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ishop_users', sa.Column('user_passwd_hash', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
