"""empty message

Revision ID: c9b37550371b
Revises: e76cfbe1cfe8
Create Date: 2020-09-26 16:54:17.757405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b37550371b'
down_revision = 'e76cfbe1cfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_address_out', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('test_address_out', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('test_user_out', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('test_user_out', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_user_out', 'update_time')
    op.drop_column('test_user_out', 'create_time')
    op.drop_column('test_address_out', 'update_time')
    op.drop_column('test_address_out', 'create_time')
    # ### end Alembic commands ###
