"""empty message

Revision ID: e76cfbe1cfe8
Revises: ed3a7e6cfc99
Create Date: 2020-09-26 16:52:11.650653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76cfbe1cfe8'
down_revision = 'ed3a7e6cfc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_address_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_address', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['test_user_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_address_out')
    # ### end Alembic commands ###
